### ISSUE TITLE
Link to formally published versions of preprints

### ISSUE THREAD

**Issue by jodischneider** [coatesj/covidpreprints#2]
When a preprint is formally published, it would be useful to link to the peer-reviewed version.

**Comment by jodischneider** [comment]
Example:

Preprint Jan 22, 2020
Functional assessment of cell entry and receptor usage for lineage B β-coronaviruses, including 2019-nCoV
https://www.biorxiv.org/content/10.1101/2020.01.22.915660v1

Formally published in Nature Feb 24 2020
Functional assessment of cell entry and receptor usage for SARS-CoV-2 and other lineage B betacoronaviruses
https://www.nature.com/articles/s41564-020-0688-y
(Interestingly - one additional author was added in the published version, and the title changed slightly)

**Comment by coatesj** [comment]
This is something we're working on adding. Should be added imminently.

**Comment by coatesj** [comment]
Links are included (further info panel) though these need to be manually copied & pasted if a user wants to follow them
