### ISSUE TITLE
Create the preprint plot dynamically

### ISSUE THREAD

**Issue by Bisaloo** [coatesj/covidpreprints#9]
I see the plot in the "Preprints posted to BioRxiv & MedRxiv" tab is included as a static png file. With shiny, it would be possible to create it on the fly and include it in the website.

I can submit a PR for this if you wish. I can re-code it from scratch or use some already existing code that you have (if it's easily available) :smile:

**Comment by coatesj** [comment]
The plot was generated by somebody else who allowedus to use it so we don't have any code. We would love to have a dynamic plot though!

**Comment by Bisaloo** [comment]
![image](https://user-images.githubusercontent.com/10783929/91972814-81743d00-ed1b-11ea-95e3-c6eaaeec0009.png)

Here is where I am right now. I still need to add a second axis with the cumulated number.

I am fetching all papers from bioRxiv API so it seems a little too expensive (in terms of computational power / bandwidth usage) to do this each time. Maybe a better alternative would be to do this once a day via GitHub actions?

**Comment by coatesj** [comment]
That's looking great. we only update the site once a week at the moment so either daily or weekly via github actions would be perfect!
